
import React, { useState } from 'react';
import '../assets/font.css'
function Fonts({onNext,onPrev,setHeadingFont, setBodyFont}) {
  const [localHeadingFont, setLocalHeadingFont] = useState('');
  const [localBodyFont, setLocalBodyFont] = useState('');

  const handleNext = (e) => {
    e.preventDefault();
    setHeadingFont(localHeadingFont);
    setBodyFont(localBodyFont);
    onNext();
  }
  return (
    <div>
      <form>
        <div className='step5-heading'>
          <div className='step5-title' >
            <h2 >Step 5 - Brand Fonts</h2>
            <p >These will be the core fonts used on your store for text. View the available fonts by clicking to see Shopify’s font library.</p>
          </div>
          <div className='step5-button head' >
            <div className='btn'>
              <button className='prev' onClick={onPrev}>Previous</button>
              <button className='prev' onClick={handleNext}>Next</button>
            </div>
          </div>
        </div>
        <div className='step5-form-content'>
          <div className='heading_fonts'>
            <div className='fonts_heading'>
              <h2 >Heading Font</h2>
              <p >This is the heading font of your brand.</p>
            </div>
            <div className='fonts_value1'>
              <p >Select a font from <b>Shopify’s font library.</b></p>
              <select  class="shopify_fonts_value" name="primary-font-select"    value={localHeadingFont}
                onChange={(e) => setLocalHeadingFont(e.target.value)}>
                <option value="" selected="" disabled="">Select Font Family</option>
                  <option value="Abel">Abel</option>
                  <option value="Abril Fatface">Abril Fatface</option>
                  <option value="Agmena">Agmena</option>
                  <option value="Akko">Akko</option>
                  <option value="Alegreya">Alegreya</option>
                  <option value="Alegreya Sans">Alegreya Sans</option>
                  <option value="Alfie">Alfie</option>
                  <option value="Americana">Americana</option>
                  <option value="Amiri">Amiri</option>
                  <option value="Anonymous Pro">Anonymous Pro</option>
                  <option value="Antique Olive">Antique Olive</option>
                  <option value="Arapey">Arapey</option>
                  <option value="Archivo">Archivo</option>
                  <option value="Archivo Narrow">Archivo Narrow</option>
                  <option value="Arimo">Arimo</option>
                  <option value="Armata">Armata</option>
                  <option value="Arvo">Arvo</option>
                  <option value="Asap">Asap</option>
                  <option value="Assistant">Assistant</option>
                  <option value="Asul">Asul</option>
                  <option value="Avenir Next">Avenir Next</option>
                  <option value="Avenir Next Rounded">Avenir Next Rounded</option>
                  <option value="Azbuka">Azbuka</option>
                  <option value="Basic Commercial">Basic Commercial</option>
                  <option value="Basic Commercial Soft Rounded">Basic Commercial Soft Rounded</option>
                  <option value="Baskerville No 2">Baskerville No 2</option>
                  <option value="Bauer Bodoni">Bauer Bodoni</option>
                  <option value="Beefcakes">Beefcakes</option>
                  <option value="Bembo Book">Bembo Book</option>
                  <option value="Bernhard Modern">Bernhard Modern</option>
                  <option value="Bio Rhyme">Bio Rhyme</option>
                  <option value="Bitter">Bitter</option>
                  <option value="Bodoni Poster">Bodoni Poster</option>
                  <option value="Burlingame">Burlingame</option>
                  <option value="Cabin">Cabin</option>
                  <option value="Cachet">Cachet</option>
                  <option value="Cardamon">Cardamon</option>
                  <option value="Cardo">Cardo</option>
                  <option value="Carter Sans">Carter Sans</option>
                  <option value="Caslon Bold">Caslon Bold</option>
                  <option value="Caslon Old Face">Caslon Old Face</option>
                  <option value="Catamaran">Catamaran</option>
                  <option value="Centaur">Centaur</option>
                  <option value="Century Gothic">Century Gothic</option>
                  <option value="Chivo">Chivo</option>
                  <option value="Chong Modern">Chong Modern</option>
                  <option value="Claire News">Claire News</option>
                  <option value="Cooper BT">Cooper BT</option>
                  <option value="Cormorant">Cormorant</option>
                  <option value="Courier New">Courier New</option>
                  <option value="Crimson Text">Crimson Text</option>
                  <option value="DIN Neuzeit Grotesk">DIN Neuzeit Grotesk</option>
                  <option value="DIN Next">DIN Next</option>
                  <option value="DIN Next Slab">DIN Next Slab</option>
                  <option value="DM Sans">DM Sans</option>
                  <option value="Daytona">Daytona</option>
                  <option value="Domine">Domine</option>
                  <option value="Dosis">Dosis</option>
                  <option value="Eczar">Eczar</option>
                  <option value="Electra">Electra</option>
                  <option value="Eurostile Next">Eurostile Next</option>
                  <option value="FF Meta">FF Meta</option>
                  <option value="FF Meta Serif">FF Meta Serif</option>
                  <option value="FF Tisa">FF Tisa</option>
                  <option value="FF Tisa Sans">FF Tisa Sans</option>
                  <option value="FF Unit">FF Unit</option>
                  <option value="FF Unit Rounded">FF Unit Rounded</option>
                  <option value="FF Unit Slab">FF Unit Slab</option>
                  <option value="FS Kim">FS Kim</option>
                  <option value="FS Koopman">FS Koopman</option>
                  <option value="FS Siena">FS Siena</option>
                  <option value="Fette Gotisch">Fette Gotisch</option>
                  <option value="Fira Sans">Fira Sans</option>
                  <option value="Fjalla One">Fjalla One</option>
                  <option value="Friz Quadrata">Friz Quadrata</option>
                  <option value="Frutiger Serif">Frutiger Serif</option>
                  <option value="Futura">Futura</option>
                  <option value="Futura Black">Futura Black</option>
                  <option value="Garamond">Garamond</option>
                  <option value="Geometric 415">Geometric 415</option>
                  <option value="Georgia Pro">Georgia Pro</option>
                  <option value="Gill Sans Nova">Gill Sans Nova</option>
                  <option value="Glegoo">Glegoo</option>
                  <option value="Goudy Old Style">Goudy Old Style</option>
                  <option value="Harmonia Sans">Harmonia Sans</option>
                  <option value="Helvetica">Helvetica</option>
                  <option value="Hope Sans">Hope Sans</option>
                  <option value="Humanist 521">Humanist 521</option>
                  <option value="IBM Plex Sans">IBM Plex Sans</option>
                  <option value="ITC Avant Garde Gothic">ITC Avant Garde Gothic</option>
                  <option value="ITC Benguiat">ITC Benguiat</option>
                  <option value="ITC Berkeley Old Style">ITC Berkeley Old Style</option>
                  <option value="ITC Bodoni Seventytwo">ITC Bodoni Seventytwo</option>
                  <option value="ITC Bodoni Twelve">ITC Bodoni Twelve</option>
                  <option value="ITC Caslon No 224">ITC Caslon No 224</option>
                  <option value="ITC Charter">ITC Charter</option>
                  <option value="ITC Cheltenham">ITC Cheltenham</option>
                  <option value="ITC Clearface">ITC Clearface</option>
                  <option value="ITC Conduit">ITC Conduit</option>
                  <option value="ITC Esprit">ITC Esprit</option>
                  <option value="ITC Founders Caslon">ITC Founders Caslon</option>
                  <option value="ITC Franklin Gothic">ITC Franklin Gothic</option>
                  <option value="ITC Galliard">ITC Galliard</option>
                  <option value="ITC Gamma">ITC Gamma</option>
                  <option value="ITC Goudy Sans">ITC Goudy Sans</option>
                  <option value="ITC Johnston">ITC Johnston</option>
                  <option value="ITC Mendoza Roman">ITC Mendoza Roman</option>
                  <option value="ITC Modern No 216">ITC Modern No 216</option>
                  <option value="ITC New Baskerville">ITC New Baskerville</option>
                  <option value="ITC New Esprit">ITC New Esprit</option>
                  <option value="ITC New Veljovic">ITC New Veljovic</option>
                  <option value="ITC Novarese">ITC Novarese</option>
                  <option value="ITC Officina Sans">ITC Officina Sans</option>
                  <option value="ITC Officina Serif">ITC Officina Serif</option>
                  <option value="ITC Stepp">ITC Stepp</option>
                  <option value="ITC Stone Humanist">ITC Stone Humanist</option>
                  <option value="ITC Stone Informal">ITC Stone Informal</option>
                  <option value="ITC Stone Sans II">ITC Stone Sans II</option>
                  <option value="ITC Stone Serif">ITC Stone Serif</option>
                  <option value="ITC Tapioca">ITC Tapioca</option>
                  <option value="Inconsolata">Inconsolata</option>
                  <option value="Inknut Antiqua">Inknut Antiqua</option>
                  <option value="Inter">Inter</option>
                  <option value="Joanna Nova">Joanna Nova</option>
                  <option value="Joanna Sans Nova">Joanna Sans Nova</option>
                  <option value="Josefin Sans">Josefin Sans</option>
                  <option value="Josefin Slab">Josefin Slab</option>
                  <option value="Kairos">Kairos</option>
                  <option value="Kalam">Kalam</option>
                  <option value="Karla">Karla</option>
                  <option value="Kreon">Kreon</option>
                  <option value="Lato">Lato</option>
                  <option value="Laurentian">Laurentian</option>
                  <option value="Libelle">Libelle</option>
                  <option value="Libre Baskerville">Libre Baskerville</option>
                  <option value="Libre Franklin">Libre Franklin</option>
                  <option value="Linotype Didot">Linotype Didot</option>
                  <option value="Linotype Gianotten">Linotype Gianotten</option>
                  <option value="Linotype Really">Linotype Really</option>
                  <option value="Linotype Syntax Serif">Linotype Syntax Serif</option>
                  <option value="Lobster">Lobster</option>
                  <option value="Lobster Two">Lobster Two</option>
                  <option value="Lora">Lora</option>
                  <option value="Lucia">Lucia</option>
                  <option value="Lucida Grande">Lucida Grande</option>
                  <option value="Luthersche Fraktur">Luthersche Fraktur</option>
                  <option value="Madera">Madera</option>
                  <option value="Malabar">Malabar</option>
                  <option value="Mariposa Sans">Mariposa Sans</option>
                  <option value="Maven Pro">Maven Pro</option>
                  <option value="Megrim">Megrim</option>
                  <option value="Melior">Melior</option>
                  <option value="Memphis">Memphis</option>
                  <option value="Memphis Soft Rounded">Memphis Soft Rounded</option>
                  <option value="Mentor Sans">Mentor Sans</option>
                  <option value="Merriweather Sans">Merriweather Sans</option>
                  <option value="Metro Nova">Metro Nova</option>
                  <option value="Modern No 20">Modern No 20</option>
                  <option value="Monaco">Monaco</option>
                  <option value="Mono">Mono</option>
                  <option value="Monotype Baskerville">Monotype Baskerville</option>
                  <option value="Monotype Bodoni">Monotype Bodoni</option>
                  <option value="Monotype Century Old Style">Monotype Century Old Style</option>
                  <option value="Monotype Goudy">Monotype Goudy</option>
                  <option value="Monotype Goudy Modern">Monotype Goudy Modern</option>
                  <option value="Monotype Italian Old Style">Monotype Italian Old Style</option>
                  <option value="Monotype New Clarendon">Monotype New Clarendon</option>
                  <option value="Monotype News Gothic">Monotype News Gothic</option>
                  <option value="Monotype Sabon">Monotype Sabon</option>
                  <option value="Montserrat">Montserrat</option>
                  <option value="Mouse Memoirs">Mouse Memoirs</option>
                  <option value="Muli">Muli</option>
                  <option value="Mundo Sans">Mundo Sans</option>
                  <option value="Neo Sans">Neo Sans</option>
                  <option value="Neue Aachen">Neue Aachen</option>
                  <option value="Neue Frutiger 1450">Neue Frutiger 1450</option>
                  <option value="Neue Haas Unica">Neue Haas Unica</option>
                  <option value="Neue Plak">Neue Plak</option>
                  <option value="Neue Swift">Neue Swift</option>
                  <option value="Neuton">Neuton</option>
                  <option value="Neuzeit Office">Neuzeit Office</option>
                  <option value="Neuzeit Office Soft Rounded">Neuzeit Office Soft Rounded</option>
                  <option value="Neuzeit S">Neuzeit S</option>
                  <option value="New Century Schoolbook">New Century Schoolbook</option>
                  <option value="News 702">News 702</option>
                  <option value="News 705">News 705</option>
                  <option value="News Cycle">News Cycle</option>
                  <option value="News Gothic No 2">News Gothic No 2</option>
                  <option value="News Plantin">News Plantin</option>
                  <option value="Nobile">Nobile</option>
                  <option value="Noticia Text">Noticia Text</option>
                  <option value="Noto Serif">Noto Serif</option>
                  <option value="Nunito">Nunito</option>
                  <option value="Nunito Sans">Nunito Sans</option>
                  <option value="Old Standard TT">Old Standard TT</option>
                  <option value="Open Sans">Open Sans</option>
                  <option value="Open Sans Condensed">Open Sans Condensed</option>
                  <option value="Optima nova">Optima nova</option>
                  <option value="Oswald">Oswald</option>
                  <option value="Ovo">Ovo</option>
                  <option value="Oxygen">Oxygen</option>
                  <option value="PMN Caecilia">PMN Caecilia</option>
                  <option value="PT Mono">PT Mono</option>
                  <option value="PT Sans">PT Sans</option>
                  <option value="PT Sans Narrow">PT Sans Narrow</option>
                  <option value="PT Serif">PT Serif</option>
                  <option value="Pacifico">Pacifico</option>
                  <option value="Palatino">Palatino</option>
                  <option value="Parma">Parma</option>
                  <option value="Perpetua">Perpetua</option>
                  <option value="Plantin">Plantin</option>
                  <option value="Playball">Playball</option>
                  <option value="Playfair Display">Playfair Display</option>
                  <option value="Poppins">Poppins</option>
                  <option value="Prata">Prata</option>
                  <option value="Prompt">Prompt</option>
                  <option value="Proza Libre">Proza Libre</option>
                  <option value="Quantico">Quantico</option>
                  <option value="Quattrocento">Quattrocento</option>
                  <option value="Quattrocento Sans">Quattrocento Sans</option>
                  <option value="Questrial">Questrial</option>
                  <option value="Quicksand">Quicksand</option>
                  <option value="Quire Sans">Quire Sans</option>
                  <option value="Rajdhani">Rajdhani</option>
                  <option value="Raleway">Raleway</option>
                  <option value="Really No 2">Really No 2</option>
                  <option value="Righteous">Righteous</option>
                  <option value="Roboto">Roboto</option>
                  <option value="Roboto Condensed">Roboto Condensed</option>
                  <option value="Roboto Mono">Roboto Mono</option>
                  <option value="Roboto Slab">Roboto Slab</option>
                  <option value="Rockwell">Rockwell</option>
                  <option value="Rubik">Rubik</option>
                  <option value="Sabon Next">Sabon Next</option>
                  <option value="Sackers Square Gothic">Sackers Square Gothic</option>
                  <option value="Sagrantino">Sagrantino</option>
                  <option value="Sans-serif">Sans-serif</option>
                  <option value="Scene">Scene</option>
                  <option value="Scherzo">Scherzo</option>
                  <option value="Serif">Serif</option>
                  <option value="Shadows Into Light">Shadows Into Light</option>
                  <option value="Slabo 13px">Slabo 13px</option>
                  <option value="Slate">Slate</option>
                  <option value="Smooch">Smooch</option>
                  <option value="Soho">Soho</option>
                  <option value="Soho Gothic">Soho Gothic</option>
                  <option value="Source Code Pro">Source Code Pro</option>
                  <option value="Source Sans Pro">Source Sans Pro</option>
                  <option value="Space Mono">Space Mono</option>
                  <option value="Stempel Schneidler">Stempel Schneidler</option>
                  <option value="Swiss 721">Swiss 721</option>
                  <option value="Swiss 721 Rounded">Swiss 721 Rounded</option>
                  <option value="Syne">Syne</option>
                  <option value="Tenor Sans">Tenor Sans</option>
                  <option value="Tiemann">Tiemann</option>
                  <option value="Times New Roman">Times New Roman</option>
                  <option value="Tinos">Tinos</option>
                  <option value="Titillium Web">Titillium Web</option>
                  <option value="Trade Gothic">Trade Gothic</option>
                  <option value="Trade Gothic Next">Trade Gothic Next</option>
                  <option value="Trebuchet MS">Trebuchet MS</option>
                  <option value="Twentieth Century">Twentieth Century</option>
                  <option value="Ubuntu">Ubuntu</option>
                  <option value="Unica One">Unica One</option>
                  <option value="Univers Next">Univers Next</option>
                  <option value="Univers Next Typewriter">Univers Next Typewriter</option>
                  <option value="Unna">Unna</option>
                  <option value="Vala">Vala</option>
                  <option value="Varela">Varela</option>
                  <option value="Varela Round">Varela Round</option>
                  <option value="Verdana Pro">Verdana Pro</option>
                  <option value="Vidaloka">Vidaloka</option>
                  <option value="Volkhov">Volkhov</option>
                  <option value="Vollkorn">Vollkorn</option>
                  <option value="Waza">Waza</option>
                  <option value="Wola">Wola</option>
                  <option value="Work Sans">Work Sans</option>
                  <option value="Ysobel">Ysobel</option>
                  <option value="Zurich">Zurich</option>
                  <option value="Zurich Extended">Zurich Extended</option>
              </select>
            </div>
          </div>
          <div className='body_fonts' >
            <div className='body_fonts_heading'>
              <h2 >Body Font</h2>
              <p >This is the Body font of your brand.</p>
            </div>
            <div className='fonts_value2'>
              <p >Select a font from <b>Shopify’s font library.</b></p>
              <select class="shopify_fonts_value" name="primary-font-select"  value={localBodyFont}
                onChange={(e) => setLocalBodyFont(e.target.value)}>
                <option value="" selected="" disabled="">Select Font Family</option>
                  <option value="Abel">Abel</option>
                  <option value="Abril Fatface">Abril Fatface</option>
                  <option value="Agmena">Agmena</option>
                  <option value="Akko">Akko</option>
                  <option value="Alegreya">Alegreya</option>
                  <option value="Alegreya Sans">Alegreya Sans</option>
                  <option value="Alfie">Alfie</option>
                  <option value="Americana">Americana</option>
                  <option value="Amiri">Amiri</option>
                  <option value="Anonymous Pro">Anonymous Pro</option>
                  <option value="Antique Olive">Antique Olive</option>
                  <option value="Arapey">Arapey</option>
                  <option value="Archivo">Archivo</option>
                  <option value="Archivo Narrow">Archivo Narrow</option>
                  <option value="Arimo">Arimo</option>
                  <option value="Armata">Armata</option>
                  <option value="Arvo">Arvo</option>
                  <option value="Asap">Asap</option>
                  <option value="Assistant">Assistant</option>
                  <option value="Asul">Asul</option>
                  <option value="Avenir Next">Avenir Next</option>
                  <option value="Avenir Next Rounded">Avenir Next Rounded</option>
                  <option value="Azbuka">Azbuka</option>
                  <option value="Basic Commercial">Basic Commercial</option>
                  <option value="Basic Commercial Soft Rounded">Basic Commercial Soft Rounded</option>
                  <option value="Baskerville No 2">Baskerville No 2</option>
                  <option value="Bauer Bodoni">Bauer Bodoni</option>
                  <option value="Beefcakes">Beefcakes</option>
                  <option value="Bembo Book">Bembo Book</option>
                  <option value="Bernhard Modern">Bernhard Modern</option>
                  <option value="Bio Rhyme">Bio Rhyme</option>
                  <option value="Bitter">Bitter</option>
                  <option value="Bodoni Poster">Bodoni Poster</option>
                  <option value="Burlingame">Burlingame</option>
                  <option value="Cabin">Cabin</option>
                  <option value="Cachet">Cachet</option>
                  <option value="Cardamon">Cardamon</option>
                  <option value="Cardo">Cardo</option>
                  <option value="Carter Sans">Carter Sans</option>
                  <option value="Caslon Bold">Caslon Bold</option>
                  <option value="Caslon Old Face">Caslon Old Face</option>
                  <option value="Catamaran">Catamaran</option>
                  <option value="Centaur">Centaur</option>
                  <option value="Century Gothic">Century Gothic</option>
                  <option value="Chivo">Chivo</option>
                  <option value="Chong Modern">Chong Modern</option>
                  <option value="Claire News">Claire News</option>
                  <option value="Cooper BT">Cooper BT</option>
                  <option value="Cormorant">Cormorant</option>
                  <option value="Courier New">Courier New</option>
                  <option value="Crimson Text">Crimson Text</option>
                  <option value="DIN Neuzeit Grotesk">DIN Neuzeit Grotesk</option>
                  <option value="DIN Next">DIN Next</option>
                  <option value="DIN Next Slab">DIN Next Slab</option>
                  <option value="DM Sans">DM Sans</option>
                  <option value="Daytona">Daytona</option>
                  <option value="Domine">Domine</option>
                  <option value="Dosis">Dosis</option>
                  <option value="Eczar">Eczar</option>
                  <option value="Electra">Electra</option>
                  <option value="Eurostile Next">Eurostile Next</option>
                  <option value="FF Meta">FF Meta</option>
                  <option value="FF Meta Serif">FF Meta Serif</option>
                  <option value="FF Tisa">FF Tisa</option>
                  <option value="FF Tisa Sans">FF Tisa Sans</option>
                  <option value="FF Unit">FF Unit</option>
                  <option value="FF Unit Rounded">FF Unit Rounded</option>
                  <option value="FF Unit Slab">FF Unit Slab</option>
                  <option value="FS Kim">FS Kim</option>
                  <option value="FS Koopman">FS Koopman</option>
                  <option value="FS Siena">FS Siena</option>
                  <option value="Fette Gotisch">Fette Gotisch</option>
                  <option value="Fira Sans">Fira Sans</option>
                  <option value="Fjalla One">Fjalla One</option>
                  <option value="Friz Quadrata">Friz Quadrata</option>
                  <option value="Frutiger Serif">Frutiger Serif</option>
                  <option value="Futura">Futura</option>
                  <option value="Futura Black">Futura Black</option>
                  <option value="Garamond">Garamond</option>
                  <option value="Geometric 415">Geometric 415</option>
                  <option value="Georgia Pro">Georgia Pro</option>
                  <option value="Gill Sans Nova">Gill Sans Nova</option>
                  <option value="Glegoo">Glegoo</option>
                  <option value="Goudy Old Style">Goudy Old Style</option>
                  <option value="Harmonia Sans">Harmonia Sans</option>
                  <option value="Helvetica">Helvetica</option>
                  <option value="Hope Sans">Hope Sans</option>
                  <option value="Humanist 521">Humanist 521</option>
                  <option value="IBM Plex Sans">IBM Plex Sans</option>
                  <option value="ITC Avant Garde Gothic">ITC Avant Garde Gothic</option>
                  <option value="ITC Benguiat">ITC Benguiat</option>
                  <option value="ITC Berkeley Old Style">ITC Berkeley Old Style</option>
                  <option value="ITC Bodoni Seventytwo">ITC Bodoni Seventytwo</option>
                  <option value="ITC Bodoni Twelve">ITC Bodoni Twelve</option>
                  <option value="ITC Caslon No 224">ITC Caslon No 224</option>
                  <option value="ITC Charter">ITC Charter</option>
                  <option value="ITC Cheltenham">ITC Cheltenham</option>
                  <option value="ITC Clearface">ITC Clearface</option>
                  <option value="ITC Conduit">ITC Conduit</option>
                  <option value="ITC Esprit">ITC Esprit</option>
                  <option value="ITC Founders Caslon">ITC Founders Caslon</option>
                  <option value="ITC Franklin Gothic">ITC Franklin Gothic</option>
                  <option value="ITC Galliard">ITC Galliard</option>
                  <option value="ITC Gamma">ITC Gamma</option>
                  <option value="ITC Goudy Sans">ITC Goudy Sans</option>
                  <option value="ITC Johnston">ITC Johnston</option>
                  <option value="ITC Mendoza Roman">ITC Mendoza Roman</option>
                  <option value="ITC Modern No 216">ITC Modern No 216</option>
                  <option value="ITC New Baskerville">ITC New Baskerville</option>
                  <option value="ITC New Esprit">ITC New Esprit</option>
                  <option value="ITC New Veljovic">ITC New Veljovic</option>
                  <option value="ITC Novarese">ITC Novarese</option>
                  <option value="ITC Officina Sans">ITC Officina Sans</option>
                  <option value="ITC Officina Serif">ITC Officina Serif</option>
                  <option value="ITC Stepp">ITC Stepp</option>
                  <option value="ITC Stone Humanist">ITC Stone Humanist</option>
                  <option value="ITC Stone Informal">ITC Stone Informal</option>
                  <option value="ITC Stone Sans II">ITC Stone Sans II</option>
                  <option value="ITC Stone Serif">ITC Stone Serif</option>
                  <option value="ITC Tapioca">ITC Tapioca</option>
                  <option value="Inconsolata">Inconsolata</option>
                  <option value="Inknut Antiqua">Inknut Antiqua</option>
                  <option value="Inter">Inter</option>
                  <option value="Joanna Nova">Joanna Nova</option>
                  <option value="Joanna Sans Nova">Joanna Sans Nova</option>
                  <option value="Josefin Sans">Josefin Sans</option>
                  <option value="Josefin Slab">Josefin Slab</option>
                  <option value="Kairos">Kairos</option>
                  <option value="Kalam">Kalam</option>
                  <option value="Karla">Karla</option>
                  <option value="Kreon">Kreon</option>
                  <option value="Lato">Lato</option>
                  <option value="Laurentian">Laurentian</option>
                  <option value="Libelle">Libelle</option>
                  <option value="Libre Baskerville">Libre Baskerville</option>
                  <option value="Libre Franklin">Libre Franklin</option>
                  <option value="Linotype Didot">Linotype Didot</option>
                  <option value="Linotype Gianotten">Linotype Gianotten</option>
                  <option value="Linotype Really">Linotype Really</option>
                  <option value="Linotype Syntax Serif">Linotype Syntax Serif</option>
                  <option value="Lobster">Lobster</option>
                  <option value="Lobster Two">Lobster Two</option>
                  <option value="Lora">Lora</option>
                  <option value="Lucia">Lucia</option>
                  <option value="Lucida Grande">Lucida Grande</option>
                  <option value="Luthersche Fraktur">Luthersche Fraktur</option>
                  <option value="Madera">Madera</option>
                  <option value="Malabar">Malabar</option>
                  <option value="Mariposa Sans">Mariposa Sans</option>
                  <option value="Maven Pro">Maven Pro</option>
                  <option value="Megrim">Megrim</option>
                  <option value="Melior">Melior</option>
                  <option value="Memphis">Memphis</option>
                  <option value="Memphis Soft Rounded">Memphis Soft Rounded</option>
                  <option value="Mentor Sans">Mentor Sans</option>
                  <option value="Merriweather Sans">Merriweather Sans</option>
                  <option value="Metro Nova">Metro Nova</option>
                  <option value="Modern No 20">Modern No 20</option>
                  <option value="Monaco">Monaco</option>
                  <option value="Mono">Mono</option>
                  <option value="Monotype Baskerville">Monotype Baskerville</option>
                  <option value="Monotype Bodoni">Monotype Bodoni</option>
                  <option value="Monotype Century Old Style">Monotype Century Old Style</option>
                  <option value="Monotype Goudy">Monotype Goudy</option>
                  <option value="Monotype Goudy Modern">Monotype Goudy Modern</option>
                  <option value="Monotype Italian Old Style">Monotype Italian Old Style</option>
                  <option value="Monotype New Clarendon">Monotype New Clarendon</option>
                  <option value="Monotype News Gothic">Monotype News Gothic</option>
                  <option value="Monotype Sabon">Monotype Sabon</option>
                  <option value="Montserrat">Montserrat</option>
                  <option value="Mouse Memoirs">Mouse Memoirs</option>
                  <option value="Muli">Muli</option>
                  <option value="Mundo Sans">Mundo Sans</option>
                  <option value="Neo Sans">Neo Sans</option>
                  <option value="Neue Aachen">Neue Aachen</option>
                  <option value="Neue Frutiger 1450">Neue Frutiger 1450</option>
                  <option value="Neue Haas Unica">Neue Haas Unica</option>
                  <option value="Neue Plak">Neue Plak</option>
                  <option value="Neue Swift">Neue Swift</option>
                  <option value="Neuton">Neuton</option>
                  <option value="Neuzeit Office">Neuzeit Office</option>
                  <option value="Neuzeit Office Soft Rounded">Neuzeit Office Soft Rounded</option>
                  <option value="Neuzeit S">Neuzeit S</option>
                  <option value="New Century Schoolbook">New Century Schoolbook</option>
                  <option value="News 702">News 702</option>
                  <option value="News 705">News 705</option>
                  <option value="News Cycle">News Cycle</option>
                  <option value="News Gothic No 2">News Gothic No 2</option>
                  <option value="News Plantin">News Plantin</option>
                  <option value="Nobile">Nobile</option>
                  <option value="Noticia Text">Noticia Text</option>
                  <option value="Noto Serif">Noto Serif</option>
                  <option value="Nunito">Nunito</option>
                  <option value="Nunito Sans">Nunito Sans</option>
                  <option value="Old Standard TT">Old Standard TT</option>
                  <option value="Open Sans">Open Sans</option>
                  <option value="Open Sans Condensed">Open Sans Condensed</option>
                  <option value="Optima nova">Optima nova</option>
                  <option value="Oswald">Oswald</option>
                  <option value="Ovo">Ovo</option>
                  <option value="Oxygen">Oxygen</option>
                  <option value="PMN Caecilia">PMN Caecilia</option>
                  <option value="PT Mono">PT Mono</option>
                  <option value="PT Sans">PT Sans</option>
                  <option value="PT Sans Narrow">PT Sans Narrow</option>
                  <option value="PT Serif">PT Serif</option>
                  <option value="Pacifico">Pacifico</option>
                  <option value="Palatino">Palatino</option>
                  <option value="Parma">Parma</option>
                  <option value="Perpetua">Perpetua</option>
                  <option value="Plantin">Plantin</option>
                  <option value="Playball">Playball</option>
                  <option value="Playfair Display">Playfair Display</option>
                  <option value="Poppins">Poppins</option>
                  <option value="Prata">Prata</option>
                  <option value="Prompt">Prompt</option>
                  <option value="Proza Libre">Proza Libre</option>
                  <option value="Quantico">Quantico</option>
                  <option value="Quattrocento">Quattrocento</option>
                  <option value="Quattrocento Sans">Quattrocento Sans</option>
                  <option value="Questrial">Questrial</option>
                  <option value="Quicksand">Quicksand</option>
                  <option value="Quire Sans">Quire Sans</option>
                  <option value="Rajdhani">Rajdhani</option>
                  <option value="Raleway">Raleway</option>
                  <option value="Really No 2">Really No 2</option>
                  <option value="Righteous">Righteous</option>
                  <option value="Roboto">Roboto</option>
                  <option value="Roboto Condensed">Roboto Condensed</option>
                  <option value="Roboto Mono">Roboto Mono</option>
                  <option value="Roboto Slab">Roboto Slab</option>
                  <option value="Rockwell">Rockwell</option>
                  <option value="Rubik">Rubik</option>
                  <option value="Sabon Next">Sabon Next</option>
                  <option value="Sackers Square Gothic">Sackers Square Gothic</option>
                  <option value="Sagrantino">Sagrantino</option>
                  <option value="Sans-serif">Sans-serif</option>
                  <option value="Scene">Scene</option>
                  <option value="Scherzo">Scherzo</option>
                  <option value="Serif">Serif</option>
                  <option value="Shadows Into Light">Shadows Into Light</option>
                  <option value="Slabo 13px">Slabo 13px</option>
                  <option value="Slate">Slate</option>
                  <option value="Smooch">Smooch</option>
                  <option value="Soho">Soho</option>
                  <option value="Soho Gothic">Soho Gothic</option>
                  <option value="Source Code Pro">Source Code Pro</option>
                  <option value="Source Sans Pro">Source Sans Pro</option>
                  <option value="Space Mono">Space Mono</option>
                  <option value="Stempel Schneidler">Stempel Schneidler</option>
                  <option value="Swiss 721">Swiss 721</option>
                  <option value="Swiss 721 Rounded">Swiss 721 Rounded</option>
                  <option value="Syne">Syne</option>
                  <option value="Tenor Sans">Tenor Sans</option>
                  <option value="Tiemann">Tiemann</option>
                  <option value="Times New Roman">Times New Roman</option>
                  <option value="Tinos">Tinos</option>
                  <option value="Titillium Web">Titillium Web</option>
                  <option value="Trade Gothic">Trade Gothic</option>
                  <option value="Trade Gothic Next">Trade Gothic Next</option>
                  <option value="Trebuchet MS">Trebuchet MS</option>
                  <option value="Twentieth Century">Twentieth Century</option>
                  <option value="Ubuntu">Ubuntu</option>
                  <option value="Unica One">Unica One</option>
                  <option value="Univers Next">Univers Next</option>
                  <option value="Univers Next Typewriter">Univers Next Typewriter</option>
                  <option value="Unna">Unna</option>
                  <option value="Vala">Vala</option>
                  <option value="Varela">Varela</option>
                  <option value="Varela Round">Varela Round</option>
                  <option value="Verdana Pro">Verdana Pro</option>
                  <option value="Vidaloka">Vidaloka</option>
                  <option value="Volkhov">Volkhov</option>
                  <option value="Vollkorn">Vollkorn</option>
                  <option value="Waza">Waza</option>
                  <option value="Wola">Wola</option>
                  <option value="Work Sans">Work Sans</option>
                  <option value="Ysobel">Ysobel</option>
                  <option value="Zurich">Zurich</option>
                  <option value="Zurich Extended">Zurich Extended</option>
              </select>
            </div>
          </div>
          <div className='step5-button end'>
            <div className='endprev' >
              <button className='endprev' >Previous</button>
              <button className='endprev' >Next</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  )
}

export default Fonts
